[package]
name = "silkenweb-macros"
version = { workspace = true }
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
description = "Silkenweb proc macros"
homepage = "https://github.com/silkenweb/silkenweb"
repository = "https://github.com/silkenweb/silkenweb"
license = "MIT OR Apache-2.0"

categories = ["gui"]
keywords = ["css"]

[lib]
proc-macro = true

[features]
sass = ["dep:grass"]

[dependencies]
silkenweb-base = { workspace = true }
syn = { workspace = true, features = ["full"] }
proc-macro-error = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
lightningcss = { workspace = true }
grass = { workspace = true, optional = true }
derive_more = { workspace = true }
