[package]
name = "silkenweb-base"
version = { workspace = true }
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
description = "Base crate for Silkenweb"
homepage = "https://github.com/silkenweb/silkenweb"
repository = "https://github.com/silkenweb/silkenweb"
license = "MIT OR Apache-2.0"

categories = ["gui", "web-programming"]
keywords = ["reactive", "web", "html", "browser", "dom"]

[features]
css-transpile = ["dep:lightningcss"]

[dependencies]
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
cssparser = { workspace = true }
lightningcss = { workspace = true, optional = true }
itertools = { workspace = true }
clonelet = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
    "Document",
    "Element",
    "History",
    "Location",
    "Performance",
    "Storage",
    "Text",
    "Window",

    "HtmlHeadElement",
    "HtmlElement",
]
