[package]
name = "silkenweb-base"
version = "0.4.0"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
edition = "2021"
description = "Base crate for Silkenweb"
homepage = "https://github.com/silkenweb/silkenweb"
repository = "https://github.com/silkenweb/silkenweb"
license = "MIT OR Apache-2.0"

categories = ["gui", "web-programming"]
keywords = ["reactive", "web", "html", "browser", "dom"]

[dependencies]
wasm-bindgen = "=0.2.84"
js-sys = "0.3.60"
cssparser = "0.29.6"
lightningcss = "=1.0.0-alpha.42"
itertools = "0.10.5"
grass = "0.12.4"

[dependencies.web-sys]
version = "0.3.60"
features = [
    "Document",
    "Element",
    "History",
    "Location",
    "Performance",
    "Storage",
    "Text",
    "Window",

    "HtmlHeadElement",
    "HtmlElement",
]
